[build]
command = "npm run build"
publish = "dist"


# Пренасочвания за SPA routing през /index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200


# Настройки за функции
[functions]
directory = "netlify/functions"